# Generated by Django 5.2.7 on 2025-10-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_from',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_until',
        ),
        migrations.AddField(
            model_name='locker',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='locker_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='locker',
            table='lockers',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
    ]
